spring:
  datasource:
    url: jdbc:mysql://localhost:3306/schedule_db
    username: root
    password: cincom256!
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true